import 'reflect-metadata';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {randomBytes,createCipheriv,createDecipheriv,generateKeyPairSync,sign,randomUUID,verify} from 'node:crypto';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {AppsScriptTokens,deriveKey,sealToken,openToken} from '../dist/appsscript.js';
import {generateScript} from '../dist/appsscript-generator.js';
import {setDataDir,schoolKey} from '../dist/config.js';
import {SettingsService,settingsPatch} from '../dist/settings.js';
import {Mailer} from '../dist/mailer.js';
process.env.NODE_ENV='test';process.env.MONGO_URI='mongodb://127.0.0.1/test';setDataDir(mkdtempSync(tmpdir()+'/cs-token-'));
function fake(){let state,nonces=new Map(),value={configured:true,schoolCode:'sss',centralUrl:'https://central.test',publicUrl:'https://school.test',mailer:{provider:'appsscript',url:'https://script.google.com/macros/s/interim/exec',secret:'interim-secret',fromName:'School'}};
 const db={settings:{findOne:()=>({lean:async()=>({value})}),updateOne:async(_,u)=>{value=u.$set.value;}},mailerStates:{findOne:()=>({lean:async()=>state&&structuredClone(state)}),create:async d=>{if(state)throw new Error('duplicate');state={...d};},findOneAndUpdate:(q,u)=>({lean:async()=>{if(!state||state.keyId!==q.keyId||state.ivCounter>=4294967295)return null;state.ivCounter+=u.$inc.ivCounter;return structuredClone(state);}}),exists:async()=>!!(state?.token&&state.expiresAt>Date.now()+30000),updateOne:async(q,u)=>{if(!state||state.keyId!==q.keyId||(q.$or&&state.lastTs&&state.lastTs>=u.$set.lastTs))return {modifiedCount:0};Object.assign(state,u.$set);for(const key of Object.keys(u.$unset||{}))delete state[key];return {modifiedCount:1};}},mailerNonces:{create:async d=>{const key=d.keyId+d.nonce;if(nonces.has(key))throw Object.assign(new Error('duplicate'),{code:11000});nonces.set(key,{...d});},updateOne:async(q,u)=>{const d=nonces.get(q.keyId+q.nonce);if(!d||d.consumed!==q.consumed||d.reservationNonce!==q.reservationNonce||d.reservedTs!==q.reservedTs||d.validUntil<=q.validUntil.$gt)return {modifiedCount:0};Object.assign(d,u.$set);return {modifiedCount:1};}}};
 const settings=new SettingsService(db),service=new AppsScriptTokens(db,settings);return {db,settings,service,get state(){return state;}};
}
function configFrom(g){return JSON.parse(g.codeGs.match(/var CS_CONFIG=(.*?);function/)[1]);}
async function envelope(f,c,changes={},extra={}){const ts=Date.now();const p={token:'test_access_token',ts,expiresAt:ts+300000,nonce:randomUUID(),...changes};const request={keyId:c.keyId,ts:p.ts,nonce:p.nonce};request.signature=sign('RSA-SHA256',Buffer.from('carpschool-appsscript-iv:'+request.keyId+':'+request.ts+':'+request.nonce),c.privateKey).toString('base64url');let iv;try{iv=Buffer.from((await f.service.reserveIv(request)).iv,'base64url');}catch{iv=randomBytes(12);}const cipher=createCipheriv('aes-256-gcm',Buffer.from(c.key,'base64url'),iv);let e={ciphertext:Buffer.concat([cipher.update(JSON.stringify(p)),cipher.final(),cipher.getAuthTag()]).toString('base64url'),iv:iv.toString('base64url'),ts:p.ts,...extra};e.signature=sign('RSA-SHA256',Buffer.from(e.ciphertext+e.iv+e.ts),c.privateKey).toString('base64url');return e;}
test('actual generated pureJS AES matches Node crypto, without WebCrypto or TextEncoder',async()=>{
 const f=fake(),g=await f.service.generate(),c=configFrom(g);const ctx=vm.createContext({Uint8Array,Uint32Array,DataView,ArrayBuffer});vm.runInContext(g.codeGs,ctx);
 assert(g.codeGs.length<40000);assert(!g.codeGs.includes(schoolKey().export({format:'pem',type:'pkcs8'})));assert.equal(f.state.privateKey,undefined);
 for(const n of [0,1,15,16,17,256,2048]){const key=randomBytes(32),iv=randomBytes(12),data=randomBytes(n);const x=createCipheriv('aes-256-gcm',key,iv);const expected=Buffer.concat([x.update(data),x.final(),x.getAuthTag()]);assert.deepEqual(Buffer.from(ctx.CS_AES.encrypt(new Uint8Array(key),new Uint8Array(iv),new Uint8Array(data))),expected);}
 assert.deepEqual(JSON.parse(g.appsscriptJson).oauthScopes,['https://www.googleapis.com/auth/gmail.send','https://www.googleapis.com/auth/script.external_request','https://www.googleapis.com/auth/script.scriptapp']);
});
test('valid push encrypts token at rest, redacts status, leaves interim settings unchanged',async()=>{const f=fake(),g=await f.service.generate();assert.deepEqual(await f.service.accept(await envelope(f,configFrom(g))),{ok:true});assert.equal(await f.service.accessToken(),'test_access_token');assert(!JSON.stringify(f.state).includes('test_access_token'));assert(!JSON.stringify(await f.service.status()).includes('test_access_token'));assert.equal((await f.settings.get()).mailer.secret,'interim-secret');assert.equal((await f.settings.get()).mailer.appsscriptMode,undefined);});
test('replay is rejected concurrently and after service reconstruction',async()=>{const f=fake(),g=await f.service.generate(),e=await envelope(f,configFrom(g));const r=await Promise.allSettled([f.service.accept(e),f.service.accept(e)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);await assert.rejects(new AppsScriptTokens(f.db,f.settings).accept(e));});
test('rotation invalidates old signatures and outstanding token',async()=>{const f=fake(),g=await f.service.generate(),e=await envelope(f,configFrom(g));await f.service.accept(e);await assert.rejects(f.service.generate(),/Confirm regeneration/);const g2=await f.service.generate(true);assert.notEqual(g.keyId,g2.keyId);await assert.rejects(f.service.accessToken());await assert.rejects(f.service.accept(await envelope(f,configFrom(g))));assert.equal((await f.service.status()).tokenValid,false);});
test('timestamp, expiry, strict framing, invalid signature and tampered GCM rejected with generic error',async()=>{const f=fake(),g=await f.service.generate(),c=configFrom(g);for(const changes of [{ts:Date.now()-301000},{ts:Date.now()+301000},{expiresAt:Date.now()+3601000},{expiresAt:Date.now()-1},{nonce:'invalid'}])await assert.rejects(f.service.accept(await envelope(f,c,changes)),/Invalid token push/);
 const e=await envelope(f,c);for(const bad of [{...e,iv:e.iv+'='},{...e,ciphertext:e.ciphertext+'='},{...e,ts:String(e.ts)},{...e,extra:true},{...e,signature:'A'.repeat(342)}])await assert.rejects(f.service.accept(bad),/Invalid token push/);
 const tampered={...e,ciphertext:(e.ciphertext[0]==='A'?'B':'A')+e.ciphertext.slice(1)};tampered.signature=sign('RSA-SHA256',Buffer.from(tampered.ciphertext+tampered.iv+tampered.ts),c.privateKey).toString('base64url');await assert.rejects(f.service.accept(tampered),/Invalid token push/);
});
test('token at rest authentication rejects tampering and other generation salt',()=>{const salt=randomBytes(32).toString('base64url'),b=sealToken('secret',salt);assert.equal(openToken(b,salt),'secret');assert.throws(()=>openToken(b,randomBytes(32).toString('base64url')));assert.throws(()=>openToken({...b,ciphertext:(b.ciphertext[0]==='A'?'B':'A')+b.ciphertext.slice(1)},salt));});
test('switch to token mode refuses unconfirmed token, SMTP secrets redacted',async()=>{const f=fake();await assert.rejects(f.settings.update({mailer:{provider:'appsscript',appsscriptMode:'token',gmailUser:'sender@test.edu'}}),/Confirm a valid/);const view=await f.settings.update(settingsPatch.parse({mailer:{provider:'smtp',smtpHost:'smtp.test',smtpPort:587,smtpSecure:false,smtpUser:'sender',smtpPassword:'smtp-secret',fromEmail:'sender@test.edu'}}));assert.equal(view.mailer.configured,true);assert.equal(view.mailer.smtpPasswordSet,true);assert(!JSON.stringify(view).includes('smtp-secret'));});
test('Google refresh uses Gmail send API and proper MIME; no real email',async t=>{const f=fake();await f.settings.update({mailer:{provider:'gmail',gmailUser:'sender@test.edu',clientId:'id',clientSecret:'oauth-secret',refreshToken:'refresh-secret'}});let calls=0;t.mock.method(globalThis,'fetch',async(url,init)=>{calls++;assert(init.signal);if(url.includes('oauth2')){assert.equal(init.body.get('grant_type'),'refresh_token');return Response.json({access_token:'mock_access_token'});}assert.equal(url,'https://gmail.googleapis.com/gmail/v1/users/me/messages/send');assert.equal(init.headers.Authorization,'Bearer mock_access_token');const mime=Buffer.from(JSON.parse(init.body).raw,'base64url').toString();assert.match(mime,/To: student@test.edu/);assert.match(mime,/Subject: Test/);assert.match(mime,/Content-Type: multipart\/alternative/);return Response.json({id:'mock'});});await new Mailer(f.settings,f.service).send('student@test.edu','Test','body','<p>body</p>');assert.equal(calls,2);});
test('token mode never falls back to interim relay, failure sanitizes secrets',async t=>{const f=fake(),g=await f.service.generate();await f.service.accept(await envelope(f,configFrom(g)));await f.settings.update({mailer:{provider:'appsscript',appsscriptMode:'token',gmailUser:'sender@test.edu'}});let calls=0;t.mock.method(globalThis,'fetch',async(url)=>{calls++;assert.equal(url,'https://gmail.googleapis.com/gmail/v1/users/me/messages/send');throw new Error('test_access_token');});await assert.rejects(new Mailer(f.settings,f.service).send('student@test.edu','Test','body'),e=>e.getStatus()===503&&!JSON.stringify(e).includes('test_access_token'));assert.equal(calls,1);});
test('generated push executes with Apps Script mocks and signs ciphertext before server decrypt',async()=>{const f=fake(),g=await f.service.generate();const props=new Map(),pushes=[],reserved=[];const signed=a=>Array.from(a,x=>x>127?x-256:x);const ctx=vm.createContext({Uint8Array,Uint32Array,DataView,ArrayBuffer,Utilities:{base64EncodeWebSafe:a=>Buffer.from(a).toString('base64url'),base64DecodeWebSafe:s=>signed(Buffer.from(s,'base64url')),newBlob:s=>({getBytes:()=>signed(Buffer.from(s))}),getUuid:randomUUID,Charset:{UTF_8:'UTF_8'},computeRsaSha256Signature:(s,key)=>signed(sign('RSA-SHA256',Buffer.from(s),key))},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},ScriptApp:{getOAuthToken:()=> 'actual_script_mock_token'},UrlFetchApp:{fetch:(url,init)=>{if(url.includes('tokeninfo'))return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({scope:'https://www.googleapis.com/auth/gmail.send',expires_in:'3600'})};if(url.endsWith('/iv')){const r=JSON.parse(init.payload),c=configFrom(g);assert(verify('RSA-SHA256',Buffer.from('carpschool-appsscript-iv:'+r.keyId+':'+r.ts+':'+r.nonce),f.state.publicKey,Buffer.from(r.signature,'base64url')));const iv=randomBytes(12);reserved.push({keyId:r.keyId,nonce:'reserved-iv:'+iv.toString('base64url'),reservationNonce:r.nonce,reservedTs:r.ts,validUntil:new Date(r.ts+300000),consumed:false});return {getResponseCode:()=>201,getContentText:()=>JSON.stringify({iv:iv.toString('base64url')})};}pushes.push(JSON.parse(init.payload));return {getResponseCode:()=>200,getContentText:()=>'{"ok":true}'};}}});vm.runInContext(g.codeGs,ctx);ctx.pushToken();assert.equal(pushes.length,1);await f.db.mailerNonces.create(reserved[0]);await f.service.accept(pushes[0]);assert.equal(await f.service.accessToken(),'actual_script_mock_token');ctx.pushToken();assert.notEqual(pushes[0].iv,pushes[1].iv);});
test('signed server IV reservations survive reconstruction, reject replay and rotation',async()=>{
 const f=fake(),g=await f.service.generate(),c=configFrom(g);
 const request=()=>{const r={keyId:g.keyId,ts:Date.now(),nonce:randomUUID()};return {...r,signature:sign('RSA-SHA256',Buffer.from('carpschool-appsscript-iv:'+r.keyId+':'+r.ts+':'+r.nonce),c.privateKey).toString('base64url')};};
 const r=request(),one=await f.service.reserveIv(r);await assert.rejects(f.service.reserveIv(r));
 const two=await new AppsScriptTokens(f.db,f.settings).reserveIv(request());assert.notEqual(one.iv,two.iv);assert.equal(Buffer.from(two.iv,'base64url').length,12);
 await assert.rejects(f.service.reserveIv({...request(),signature:'A'.repeat(342)}));await f.service.generate(true);await assert.rejects(f.service.reserveIv(request()));
});
test('appsscript_push is explicit and cannot accidentally select the legacy relay',async t=>{const f=fake();await assert.rejects(f.settings.update({mailer:{provider:'appsscript_push'}}));const g=await f.service.generate();await f.service.accept(await envelope(f,configFrom(g)));await f.settings.update(settingsPatch.parse({mailer:{provider:'appsscript_push',gmailUser:'sender@test.edu'}}));let calls=0;t.mock.method(globalThis,'fetch',async(url)=>{calls++;assert.equal(url,'https://gmail.googleapis.com/gmail/v1/users/me/messages/send');return Response.json({id:'fake'});});await new Mailer(f.settings,f.service).send('student@test.edu','Test','body');assert.equal(calls,1);});

test('unreserved IV and reservation nonce mismatch fail closed',async()=>{
 const f=fake(),g=await f.service.generate(),c=configFrom(g),e=await envelope(f,c);
 const ts=e.ts,iv=Buffer.from(e.iv,'base64url'),p={token:'fake_token',expiresAt:ts+300000,ts,nonce:randomUUID()},cipher=createCipheriv('aes-256-gcm',Buffer.from(c.key,'base64url'),iv);
 const bad={ciphertext:Buffer.concat([cipher.update(JSON.stringify(p)),cipher.final(),cipher.getAuthTag()]).toString('base64url'),iv:e.iv,ts};bad.signature=sign('RSA-SHA256',Buffer.from(bad.ciphertext+bad.iv+bad.ts),c.privateKey).toString('base64url');
 await assert.rejects(f.service.accept(bad));await f.service.accept(e);await assert.rejects(new AppsScriptTokens(f.db,f.settings).accept(e));
});
